### ISSUE TITLE
There is no theme configuration. The file theme.json is missing from the main directory.

### ISSUE THREAD

**Issue by jarahacker** [Nyxiie/sellix-shoppy-template#4]
Hello i tryed it today and it gave me this error: There is no theme configuration. The file theme.json is missing from the main directory.
Can you please help me?

**Comment by Nyxiie** [comment]
Mh doesnt look like it its a problem with my project its more a problem on your side. Could you describe it more please?

**Comment by OskarCornejo** [comment]
same
i coukd upload it to sellix

**Comment by OskarCornejo** [comment]
couldnt

**Comment by Nyxiie** [comment]
ah now i understand this, isnt a theme for sellix/shoppy or anything its a full pledged site for your own webhost!
